name: "StartStop CI"
on:
  workflow_dispatch:
jobs:
  windows-build-released-native:
    name: Windows - Native build
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 17 ]
        graalvm-version: [ mandrel-latest ]
        graalvm-java-version: [ "21" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'maven'
      - name: Setup GraalVM
        id: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.graalvm-java-version }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
